### ISSUE TITLE
App does not open when Android debug option is on 

### ISSUE THREAD

**Issue by codeanit** [DrishtiNP/Drishti#12]
First of, this is a great initiative. Good to know about the project.

The issue is, I just installed the app and while opening the app, the messaged popped up and it did not allow me to open the app.

I am just curious to know about it. Why are we not allowing the app to run in such environment? I believe it would help to debug better.

Android Version: 6.0
Phone: Huawei 

Thanks.

**Comment by codeanit** [comment]
The issue might have been with the phone. After turning the developer mode-off and on, app is open but unfortunately it crashes while the screen is tapped.

To verify it's functionality and this issue, installed the app on other Android phone.
Android Version: 11
Phone: Galaxy A50s

There was no problem while opening up the app.
The screen tap reads the cash but it's reading wrong value.

Scanned for 100 rupees but the the voice over is 50 rupees and the data stored is also the same.

Well occasionally it reads 100 and sometimes it does not even read. So I believe that there are more issues in regards to the correct functionality.

For the main issue, I believe that as it might have just been with a device, therefore, the issue can be closed.

Thanks.

**Comment by basnetsoyuj** [comment]
thank you for the update. Yeah, we're currently working on the accuracy of the model.
